[formats]
ok_fmt = "%d(%F %T).%ms %V - %m%n"
error_fmt = "%d(%F %T).%ms %V (%F:%L) - %m%n"
rx_fmt = "%d(%F %T).%ms %V - %m%n"

[rules]
ok.DEBUG     >stdout;         ok_fmt
error.WARN   >stderr;         error_fmt
error.WARN   "errors.log";    error_fmt

rx.DEBUG     "rx.log";        rx_fmt
rx.INFO      "rx.log";        rx_fmt
rx.WARN      "rx.log";        rx_fmt
rx.ERROR     "rx.log";        rx_fmt
